theme: jekyll-theme-slate
title: LIS 198: Introduction to Digital Humanities
description: This course will examine different digital tools and techniques use by humanists in their research and explore relationship between those tools and techniques with the  information sciences.
